EIP Motivation and Specification for "Multi-operator, per-token ERC721 approval.
proofxyz/EIPs pull request #1
Opened 2023-02-02 14:01 UTC by aschlosberg

This is a first pass at the EIP's `Motivation` and `Specification` sections, based on the EIP template from `ethereum/EIPS`.

The code in the `Specification` section of the markdown is copied exactly from `assets/eip-draft…/contracts/IERCTBD.sol` so please review the Solidity instead (I will copy to the markdown before merging).

2023-02-02 14:09 UTC, aschlosberg reviewed
Testing Reviewable access to the repo.

> *[Reviewable](https://reviewable.io/reviews/proofxyz/EIPs/1#-:-NNHSU9e58C_LfRWoWjb:b-maar91)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-07 10:33 UTC, cxkoda requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/proofxyz/EIPs/1)* status: all files reviewed, 35 unresolved discussions (waiting on @aschlosberg)

___
*[`.gitignore` line 10 at r1](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNer7_n7HM2dzUuEHVA:-NNer7_o6pasXhWheODc:bhcafjc) ([raw file](https://github.com/proofxyz/EIPs/blob/7d9cd619fbbe7c82fdd3c94661b625e23bc1493f/.gitignore#L10)):*
> ```ignore
> .gitpod.yml
> .DS_Store
> /.idea
> ```

I don't know if we are allowed to change files outside our EIP. But let's keep it in and see what the editors say.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 3 at r1](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNerMYU2jRosRJ5lrSA:-NNerMYU2jRosRJ5lrSB:b-n4sjaj) ([raw file](https://github.com/proofxyz/EIPs/blob/7d9cd619fbbe7c82fdd3c94661b625e23bc1493f/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L3)):*
> ```Solidity
> // SPDX-License-Identifier: MIT
> // Copyright 2023 PROOF Holdings Inc
> pragma solidity >=0.8.16 <0.9.0;
> ```

Do we need any version-specific language features that bind us to `>=0.8.16`? If not, it might be worth to lower this to `^0.8.0` and to remove the upper limit since we only have an interface in this file.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 5 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNeu6eB7x23aRa-qgCk:-NNeu6eB7x23aRa-qgCl:b-a2ucg3) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L5)):*
> ```Solidity
> pragma solidity >=0.8.16 <0.9.0;
> 
> /**
> ```

Please add a `@notice` to briefly describe the purpose.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 8 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfPhyx8i_z2iMqQoEh:-NNfPhyx8i_z2iMqQoEi:b-8d9tnr) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L8)):*
> ```Solidity
>  * @dev Implementers concerned about the interplay between explicit approvals and the standard `ERC721` mechanisms MAY
>  *      choose to revert on all calls to `ERC721.setApprovalForAll(…)` to reduce risk exposure and make it easier to
>  *      reason about approvals. Off-chain indexers of approvals SHOULD assume that an operator is approved if either of
> ```

I think we should not explicitly encourage this since:
- we would break back-wards compatibility but have no way to identify if a contract is doing this or not
- overhead for marketplaces going against the goal `Minimal overhead to integrate`



_Code quote:_
```Solidity
 * @dev Implementers concerned about the interplay between explicit approvals and the standard `ERC721` mechanisms MAY
 *      choose to revert on all calls to `ERC721.setApprovalForAll(…)` to reduce risk exposure and make it easier to
 *      reason about approvals. Off-chain indexers of approvals SHOULD assume that an operator is approved if either of
```
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 10 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNeuLE_3S404WGE_PaJ:-NNeuLE_3S404WGE_PaK:b-bdoav9) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L10)):*
> ```Solidity
>  *      reason about approvals. Off-chain indexers of approvals SHOULD assume that an operator is approved if either of
>  *      `ERC721.Approval(…)` or `ERC721.ApprovalForAll(…, true)` events are witnessed without the corresponding
>  *      revocation(s).
> ```

I think we should remove manual indentations because the text might be parsed wrongly by doc tools. Applies to all comments in this file.



_Code quote:_
```Solidity
 * @dev Implementers concerned about the interplay between explicit approvals and the standard `ERC721` mechanisms MAY
 *      choose to revert on all calls to `ERC721.setApprovalForAll(…)` to reduce risk exposure and make it easier to
 *      reason about approvals. Off-chain indexers of approvals SHOULD assume that an operator is approved if either of
 *      `ERC721.Approval(…)` or `ERC721.ApprovalForAll(…, true)` events are witnessed without the corresponding
 *      revocation(s).
```
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 10 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfPWPS2pt7s4FGEEYm:-NNfPWPT8ZV_rbd3RqNY:bd5ft0n) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L10)):*
> ```Solidity
>  *      reason about approvals. Off-chain indexers of approvals SHOULD assume that an operator is approved if either of
>  *      `ERC721.Approval(…)` or `ERC721.ApprovalForAll(…, true)` events are witnessed without the corresponding
>  *      revocation(s).
> ```

Do we need to specify this here? Isn't this part of ERC721?



_Code quote:_
```Solidity
 *      reason about approvals. Off-chain indexers of approvals SHOULD assume that an operator is approved if either of
 *      `ERC721.Approval(…)` or `ERC721.ApprovalForAll(…, true)` events are witnessed without the corresponding
 *      revocation(s).
```
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 11 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfJ3Ga66Bs_f3zkcOf:-NNfJ3Ga66Bs_f3zkcOg:bvcpz3f) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L11)):*
> ```Solidity
>  *      `ERC721.Approval(…)` or `ERC721.ApprovalForAll(…, true)` events are witnessed without the corresponding
>  *      revocation(s).
>  */
> ```

add todo note: `* The ERC-165 identifier for this interface is TBD.`
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 12 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfHFzeA9cxom6lbKUy:-NNfHFzeA9cxom6lbKUz:b-2ypuyt) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L12)):*
> ```Solidity
>  *      revocation(s).
>  */
> interface IERCTBD {
> ```

missing inheritance `inferface IERCTBD is IERC721 {`
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 14 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNevHYOCLB_JszED4iQ:-NNevHYOCLB_JszED4iR:b6uso1b) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L14)):*
> ```Solidity
> interface IERCTBD {
>     /**
>      * @notice Emitted when an operator is explicitly enabled or disabled for a token.
> ```

`approval is explicitly granted or revoked`



_Code quote:_
```Solidity
is explicitly enabled or disabled 
```
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 32 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNevrZW6m6YCnIBwenz:-NNevrZW6m6YCnIBweo-:b-xepjfu) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L32)):*
> ```Solidity
>      * @notice Emitted when all explicit approvals, as granted by either `setExplicitApprovalFor()` function, are
>      *         revoked for the specific token.
>      * @dev MUST be emitted upon token transfer and calls to `revokeAllExplicitApprovals(tokenId)`.
> ```

I'd remove th [...]

2023-02-07 12:36 UTC, aschlosberg reviewed
Only partially responded. Publishing my comments so the align with my last commit and so those I've addressed are hidden.

> *[Reviewable](https://reviewable.io/reviews/proofxyz/EIPs/1#-:-NNfs7tN9DXc44uhSiB9:b66bqu7)* status: all files reviewed, 35 unresolved discussions (waiting on @cxkoda)

___
*[`.gitignore` line 10 at r1](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNer7_n7HM2dzUuEHVA:-NNfnDtw0ZiBpDl-GMbQ:b-1b0imk) ([raw file](https://github.com/proofxyz/EIPs/blob/7d9cd619fbbe7c82fdd3c94661b625e23bc1493f/.gitignore#L10)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

I don't know if we are allowed to change files outside our EIP. But let's keep it in and see what the editors say.
</blockquote></details>

I thought I'd chance it because it's just another common editor.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 3 at r1](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNerMYU2jRosRJ5lrSA:-NNfnLlI9HLFEHWq1Lxb:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/7d9cd619fbbe7c82fdd3c94661b625e23bc1493f/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L3)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Do we need any version-specific language features that bind us to `>=0.8.16`? If not, it might be worth to lower this to `^0.8.0` and to remove the upper limit since we only have an interface in this file.
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 5 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNeu6eB7x23aRa-qgCk:-NNfn_Yq3HAvBnk8Aks4:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L5)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Please add a `@notice` to briefly describe the purpose.
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 8 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfPhyx8i_z2iMqQoEh:-NNfngBZ1zC4Ha_pwG4I:b-g7dbwr) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L8)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

I think we should not explicitly encourage this since:
- we would break back-wards compatibility but have no way to identify if a contract is doing this or not
- overhead for marketplaces going against the goal `Minimal overhead to integrate`
</blockquote></details>

I think it needs to be said *somewhere* but I'm not fussed about where. Perhaps in the `Backwards Compatibility` section of the markdown?
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 10 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNeuLE_3S404WGE_PaJ:-NNfo_oK0sAMGL-1WAtM:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L10)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

I think we should remove manual indentations because the text might be parsed wrongly by doc tools. Applies to all comments in this file.
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 10 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfPWPS2pt7s4FGEEYm:-NNfop-V9gslgvJfNMt2:b-8d0blb) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L10)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Do we need to specify this here? Isn't this part of ERC721?
</blockquote></details>

I've clarified with ", even if an `ExplicitApprovalFor(…, false)` is emitted"
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 11 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfJ3Ga66Bs_f3zkcOf:-NNfozB57Qy03kLIlDGh:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L11)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

add todo note: `* The ERC-165 identifier for this interface is TBD.`
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 14 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNevHYOCLB_JszED4iQ:-NNfpJ0O-l-eOSAR4Mxs:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L14)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

`approval is explicitly granted or revoked`
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 33 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNexeTA1e7FDXbhxR5g:-NNfpsdI3TS6HD-6_3B8:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L33)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

I think this needs to be discussed in the EIP rationale, not in the `sol` interface, because it does not add information that helps the dev.
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 46 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNezMAX9UFVmsqWsptX:-NNfqYyL090jUVCMNeZB:b-cyx6ty) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L46)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Already included in `akin to calling revokeAll..`
</blockquote></details>

I don't think so because the first part of the sentence suggests that it's just the approvals that need to be cleared, which leaves event emission ambiguous.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 69 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNezlnDEBQepE5Cx_X_:-NNfqxq94UhkokQ5qyvq:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L69)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

This sounds a bit complicated to me. What do you think about `Revokes all explicit approvals granted by msg.sender`?
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 76 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNf-FHL4FRAHB2YpZT1:-NNfr32CE02Z2C_lkfOY:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L76)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Same as above. Maybe `Revokes all explicit approvals granted by msg.sender for a specified token`
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 94 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfM8TIEjdpO5vM5zim: [...]

2023-02-07 13:52 UTC, cxkoda requested changes
Resolved the addressed comments.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/proofxyz/EIPs/1#-:-NNg5dX70Kc4_r4dt4TR:buli14r)* status: all files reviewed, 24 unresolved discussions (waiting on @aschlosberg)

___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 3 at r1](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNerMYU2jRosRJ5lrSA:-NNg26Eo9PIDynwB4QcS:ba4z0qd) ([raw file](https://github.com/proofxyz/EIPs/blob/7d9cd619fbbe7c82fdd3c94661b625e23bc1493f/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L3)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There's unfortunately nothing concrete in the solidity docs, but I think this needs to be `^` instead of `>=` if we don't have a range.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 8 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfPhyx8i_z2iMqQoEh:-NNg2pDaEbgD4wnDyilh:bb5flww) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L8)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

I think it needs to be said *somewhere* but I'm not fussed about where. Perhaps in the `Backwards Compatibility` section of the markdown?
</blockquote></details>

Hmm, I'm a bit thorn about suggesting to break ERC721-compliance at all without a possibility to inspect it.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 46 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNezMAX9UFVmsqWsptX:-NNg4T7U387gbzho4oBs:b24mwxq) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L46)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

I don't think so because the first part of the sentence suggests that it's just the approvals that need to be cleared, which leaves event emission ambiguous.
</blockquote></details>

Fair, then I'd suggest rephrasing the first sentence using `MUST be revoked` instead of `MUST be cleared` and using `equivalent to` instead of `akin to`.
I think we just need to specify that every grant/revocation MUST emit the related event, regardless of the circumstance in which they were executed.
___
*[`EIPS/eip-draft_multi-operator_per-token_erc721_approval.md` line 4 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNf2jU-1HvVLx3f4ax2:-NNg5O9Q5tqd3lY4mQoo:bd9t5wn) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/EIPS/eip-draft_multi-operator_per-token_erc721_approval.md#L4)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

These two need to be flipped for alphabetic ordering.
</blockquote></details>

Solved. See comment below.
___
*[`EIPS/eip-draft_multi-operator_per-token_erc721_approval.md` line 14 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNf3C6XAAf7Mx8wTzYw:-NNg5QX_EH7PwIbGpqN8:bauiasf) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/EIPS/eip-draft_multi-operator_per-token_erc721_approval.md#L14)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

Hehe I did it as Garner before he gave me his name! Done.
</blockquote></details>

This ended up on the wrong comment. Resolved the other one.


<!-- Sent from Reviewable.io -->

2023-02-07 16:50 UTC, aschlosberg reviewed
> *[Reviewable](https://reviewable.io/reviews/proofxyz/EIPs/1)* status: all files reviewed, 23 unresolved discussions (waiting on @cxkoda)

___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 3 at r1](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNerMYU2jRosRJ5lrSA:-NNgF-Q21Z193b-oQ1rf:bd5i9fm) ([raw file](https://github.com/proofxyz/EIPs/blob/7d9cd619fbbe7c82fdd3c94661b625e23bc1493f/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L3)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

There's unfortunately nothing concrete in the solidity docs, but I think this needs to be `^` instead of `>=` if we don't have a range.
</blockquote></details>

No idea. `solc` doesn't complain either way, but I've changed to `^`.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 8 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfPhyx8i_z2iMqQoEh:-NNgF4tf2S5aw9fLJYJq:b-dripe1) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L8)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Hmm, I'm a bit thorn about suggesting to break ERC721-compliance at all without a possibility to inspect it.
</blockquote></details>

Then lets include a full discussion around it in the rationale.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 12 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfHFzeA9cxom6lbKUy:-NNgHF7-1fYIcMBtvzpB:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L12)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

missing inheritance `inferface IERCTBD is IERC721 {`
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 32 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNevrZW6m6YCnIBwenz:-NNglZGmEYoPR2tesLPF:b-qskei9) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L32)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

I'd remove this part as it can be misunderstood as "Only the event needs to be emitted during transfers" whereas we want to specify that "Approvals must be revoked on transfers, and the event must be emitted in all revocations" (not limited to transfers and `revokeAllExplicitApprovals(tokenId)`). I'd move this to a `@dev` note in the header.
On second thought, I think the entire `@dev` note can be removed since the full intent is already given in the `@notice` and we don't add any new information here. Also, a note on `revokeAllExplicitApprovals(tokenId)` specifies that it must be emitted there.  
</blockquote></details>

I've just removed the single line.

We should just codify all of our intents into an official test suite.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 44 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNeyrAr395HObUTxvAE:-NNgf1P_4TteW0o8oRq9:b4eiyfw) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L44)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

For the sake of ERC721 compatibility, I think this should not throw if the caller is approved.
If we want to enforce this, we need to address the deviation in the `Rationale`.
</blockquote></details>

Done. I just hadn't read the full sentence in the `approve()` comments :)
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 46 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNezMAX9UFVmsqWsptX:-NNgFT8U2-DX29Lswlf1:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L46)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Fair, then I'd suggest rephrasing the first sentence using `MUST be revoked` instead of `MUST be cleared` and using `equivalent to` instead of `akin to`.
I think we just need to specify that every grant/revocation MUST emit the related event, regardless of the circumstance in which they were executed.
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 77 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNf-PUBCGkBZ5RQ89aS:-NNgf9rQ2V_-ju690aCI:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L77)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Same as for `setExplicitApproval`, approved callers should be exempt. 
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 86 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNf1BZY27HR4nA55xHM:-NNgFn057yTew4r3Mltg:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L86)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

I think we are overspecifying things here, since the consumer is free to implement other methods to set/revoke explicit approvals. IMO this should only read as `@notice Query if an address is an authorized operator for a token` because we already defined what an approval is conceptually (i.e. not tied to `setExplicitApprovalFor()`) and when they need to be automatically revoked. 
</blockquote></details>

Done.
___
*[`EIPS/eip-draft_multi-operator_per-token_erc721_approval.md` line 14 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNf3C6XAAf7Mx8wTzYw:-NNgfN3A263UKlGg83Rb:b-3glkr5) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/EIPS/eip-draft_multi-operator_per-token_erc721_approval.md#L14)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

This ended up on the wrong comment. Resolved the other one.
</blockquote></details>

Whoops! Done. I went with `specific`.
___
*[`EIPS/eip-draft_multi-operator_per-token_erc721_approval.md` line 14 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNf3vdsCm1uTFXdEyoI:-NNgfpcVCn2H29WJZxJW:bluclyd) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/EIPS/eip-draft_multi-operator_per-token_erc721_approval.md#L14)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

I'd flip the first and second sentence and reformulate a bit to have an `context -> problem -> solution -> results` structure.

```
The ERC721 standard did not foresee the approval of multiple operators to manage a specific token on behalf of their owner. 
This lead to the establishment of `setApprovalForAll()` as the predominant way to authorise operators, which affords the approved address control over all assets and creates an unnecessarily broad security risk that has already been exploited in a multitude of phishing attacks.
The presented EIP extends ERC721 by introducing a fine-grained, on-chain approval mechanism that allows owners to authorise multiple operators on a per-token basis.
[Being explicit about the benefits: This removes unnecessary access permissions and shrinks the surface for exploits to a m [...]

2023-02-08 13:42 UTC, aschlosberg reviewed
> *[Reviewable](https://reviewable.io/reviews/proofxyz/EIPs/1)* status: all files reviewed, 3 unresolved discussions (waiting on @cxkoda)

___
*[`.gitmodules` line 3 at r4](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNl6DiP67z7B_3ipc6a:-NNlCKUL-iVyiwl20CqF:b-zay2o0) ([raw file](https://github.com/proofxyz/EIPs/blob/6806b2dd3b3a13d19447ca0fcf621bbd6b5d1ecf/.gitmodules#L3)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Why are we including OZ as submodule?
</blockquote></details>

I figured we'd need a full implementation of ERC721 for the test suite. For now I've just explicitly copied over `IERC{165,721}.sol` from OZ and we can assess need for a full implementation once we write the test suite.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 8 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfPhyx8i_z2iMqQoEh:-NNlD1GM4PYp2AwKXkGE:b-z7us2p) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L8)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

I think that is too prominent. I think it should only be a sidenote somewhere since it's not part of what we are trying to spec in this EIP.
</blockquote></details>

I've removed it from here and have a TODO in the `Other risks` section of `Security Considerations`, which we only have to complete if we wish to move beyond draft.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/lib/openzeppelin-contracts` line 1 at r4](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNl6JdFAuAqBIuEEJTI:-NNlENXEDkTis5V-CNyI:bdgagfe) ([raw file](https://github.com/proofxyz/EIPs/blob/6806b2dd3b3a13d19447ca0fcf621bbd6b5d1ecf/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/lib/openzeppelin-contracts#L1)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Same as for `.gitmodules`
</blockquote></details>

Same as for my reply re `.gitmodules`
___
*[`EIPS/eip-draft_multi-operator_per-token_erc721_approval.md` line 18 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfD-tb0KbWTpUqu0bd:-NNlET47EPzHI-LTFcQW:bku0wai) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/EIPS/eip-draft_multi-operator_per-token_erc721_approval.md#L18)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

ohhh TIL! I always (wrongly) used a normal dash + spaces instead of an em dash.
</blockquote></details>

Hyphen :wink: 

Typography is beautiful when done correctly, and it aligns nicely with a programmer's mindset.
___
*[`EIPS/eip-draft_multi-operator_per-token_erc721_approval.md` line 23 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfEIJa9Cdzai9uiWnD:-NNlEjpa1kns1VX9z7XU:b7v41cp) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/EIPS/eip-draft_multi-operator_per-token_erc721_approval.md#L23)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

We could cite without links - just like classical journals.
</blockquote></details>

I've asked OS for numbers so let's reassess if/when we get any. Not necessary for getting a draft PR on the EIPs repo.
___
*[`EIPS/eip-draft_multi-operator_per-token_erc721_approval.md` line 31 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfG79UEOjMNpEYGwRB:-NNlFDM9AT-eOhBcR3-8:b-u6cdy5) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/EIPS/eip-draft_multi-operator_per-token_erc721_approval.md#L31)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

I always understood "simplified" as "something being simpler than before". Since we have no status quo for explicit approvals, I'd therefore use `simple`. but this is quite nit-picky, and I'm not a native - so I'm happy to let you decide.
</blockquote></details>

Nah, you're correct. I'm implicitly comparing to the naive solution (1 grant = 1 revocation), but I've also been told that I have some weird idiosyncrasies when I write! 
___
*[`EIPS/eip-draft_multi-operator_per-token_erc721_approval.md` line 42 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfLCXf4la6iXMni7KH:-NNlF_GI9PiTTBzYCVoV:b-mjx70o) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/EIPS/eip-draft_multi-operator_per-token_erc721_approval.md#L42)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Yes, sorry.
</blockquote></details>

We've already got it in a `@dev` line of the interface.


<!-- Sent from Reviewable.io -->

2023-02-08 14:34 UTC, cxkoda approved these changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/proofxyz/EIPs/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aschlosberg)

___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol` line 8 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfPhyx8i_z2iMqQoEh:-NNlRG5U9VGA7XtE5ic-:b-hfghm4) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/IERCTBD.sol#L8)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

I've removed it from here and have a TODO in the `Other risks` section of `Security Considerations`, which we only have to complete if we wish to move beyond draft.
</blockquote></details>

Sounds good
___
*[`EIPS/eip-draft_multi-operator_per-token_erc721_approval.md` line 42 at r2](https://reviewable.io/reviews/proofxyz/EIPs/1#-NNfLCXf4la6iXMni7KH:-NNlRaQn7Pvv9skNILzJ:bb74x83) ([raw file](https://github.com/proofxyz/EIPs/blob/b7673b8efdfc06a389038e2e0fdb01a384d09702/EIPS/eip-draft_multi-operator_per-token_erc721_approval.md#L42)):*
<details><summary><i>Previously, aschlosberg (Arran Schlosberg) wrote…</i></summary><blockquote>

We've already got it in a `@dev` line of the interface.
</blockquote></details>

True


<!-- Sent from Reviewable.io -->

2023-02-08 14:45 UTC, merged