Crisgarner/erc721 per token approval
proofxyz/EIPs pull request #6
Opened 2023-02-08 17:25 UTC by crisgarner

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2023-02-10 14:41 UTC, cxkoda requested changes
Please move `assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/` -> `assets/eip-6464/reference-implementation` and rename all instances of `ERCTBD` to `ERC6464`



Think about splitting off the events into a separate interface that is immediately inherited.

> Reviewed 56 of 56 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/proofxyz/EIPs/6#-:-NNqQZE_9LZtwdtv1z8s:b-t99ika)* status: all files reviewed, 25 unresolved discussions (waiting on @crisgarner)

___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/README.md` line 3 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqQ17Y0rTTH8woozFH:-NNqQ17Y0rTTH8woozFI:b-spsuwf) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/README.md#L3)):*
> ```Markdown
> # ERCTBD Reference Implementations
> 
> This is the source code for a reference implementation of ERCTBD.
> ```

Please rename to EIP-6464



_Code quote:_
```Markdown
ERCTBD
```
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/README.md` line 7 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqQLViEVbrdQNNbt7J:-NNqQLVj4himl2Mo4aYl:b-kjqmv) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/README.md#L7)):*
> ```Markdown
> ## Build and Test
> 
> The repo expects a [Foundry](https://github.com/foundry-rs/foundry/tree/master/forge) build system. You can run the test suite with:
> ```

Not just build system but also as test runner. Maybe rephrase to `.. expects [Foundry](..) to be installed.`?



_Code quote:_
```Markdown
a [Foundry](https://github.com/foundry-rs/foundry/tree/master/forge) build system
```
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 7 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqSCUa9JuL4GTDH2aa:-NNqSCUb0eghRRrWAzmG:bj2u728) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L7)):*
> ```Solidity
> import "./utils/ERC721.sol";
> 
> contract ERCTBD is ERC721, IERCTBD, IERCTBDAnyApproval {
> ```

If you make this contract `abstract` you can skip the constructor and leave it to the consuming contract. See also [ERC721Enumerable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/ERC721Enumerable.sol)
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 7 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqYgc7CEVl7DpTH33V:-NNqYcKEAiSMC3HwR1Oe:bks9z59) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L7)):*
> ```Solidity
> import "./utils/ERC721.sol";
> 
> contract ERCTBD is ERC721, IERCTBD, IERCTBDAnyApproval {
> ```

Any opinions about doing separate implementations for `IERCTBD` and `...AnyApproval`?
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 12 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqSZyG7c01zBAS9jEO:-NNqSZyH3-dCkDv9eDQw:b-v1b8vk) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L12)):*
> ```Solidity
>     //////////////////////////////////////////////////////////////*/
> 
>     uint256 counter = 0;
> ```

All variables and functions need at least an `@notice` explaining the basic use/intent of the object. Please also specify all visibilities (i.e. `private` in this case) explicitly and use a leading underscore for `private` and `internal` ones. 
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 15 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqT3l7-KlpGRgag_kn:-NNqT3l7-KlpGRgag_ko:b-75em9s) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L15)):*
> ```Solidity
>     /// @dev Nonces used for revokes cleanup
>     mapping(uint256 => uint256) private _tokenNonce;
>     mapping(address => uint256) private _ownerNonce;
> ```

We can introduce [user-defined value types](https://docs.soliditylang.org/en/latest/types.html#user-defined-value-types) here to make these and the following mapping type safe. i.e. something like 
```
type TokenNonce is uint256;
mapping(uint256 => TokenNonce) private _tokenNonces;
```



_Code quote:_
```Solidity
    mapping(uint256 => uint256) private _tokenNonce;
    mapping(address => uint256) private _ownerNonce;
```
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 19 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqTpNDDSJIxgmwdUzG:-NNqTpNDDSJIxgmwdUzH:b-u046fg) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L19)):*
> ```Solidity
>     /// @dev tokenId -> tokenNonce -> ownerNounce -> operator -> approval
>     mapping(uint256 => mapping(uint256 => mapping(uint256 => mapping(address => bool))))
>         private _isExplicitlyApprovedFor;
> ```

Using the above types, this would translate to `mapping(uint => mapping(TokenNonce => mapping(OwnerNonce => mapping(address => bool))))`



_Code quote:_
```Solidity
    mapping(uint256 => mapping(uint256 => mapping(uint256 => mapping(address => bool))))
        private _isExplicitlyApprovedFor;
```
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 26 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqYszb33bN2rCUjKkF:-NNqYszb33bN2rCUjKkG:b4b6k4m) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L26)):*
> ```Solidity
>     constructor(string memory _name, string memory _symbol)
>         ERC721(_name, _symbol)
>     {}
> ```

Not needed for the reference implementation



_Code quote:_
```Solidity
    /*//////////////////////////////////////////////////////////////
                      ERC721 IMPLEMENTATION FOR TESTING
    //////////////////////////////////////////////////////////////*/
    constructor(string memory _name, string memory _symbol)
        ERC721(_name, _symbol)
    {}
```
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 31 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqYuclBrbBBC8jBYHS:-NNqYuclBrbBBC8jBYHT:b-33dhb4) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L31)):*
> ```Solidity
>         _mint(_receiver, counter);
>         counter++;
>     }
> ```

Since the reference implementation should be easily reusable we should not add any public functions that are outside the spec, especially if they are as dangerous as this one.



_Code quote:_
```Solidity
    function mint(address _receiver) external {
        _mint(_receiver, counter);
        counter++;
    }
```
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 41 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqUq8g-_lxhMTyFCsY:-NNqUq8g-_lxhMTyFCsZ:b-8pr00v) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L41)):*
> ```Solidity
>         require(to != address(0), "INVALID_RECIPIENT");
>         /// @de [...]

2023-02-10 21:36 UTC, crisgarner commented
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 7 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqYgc7CEVl7DpTH33V:-NNxF9lG4btY8lY2w_oi:b-w61kxj) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L7)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Any opinions about doing separate implementations for `IERCTBD` and `...AnyApproval`?
</blockquote></details>

Another abstract contract that implements the IERC6464 and then inherits to ERC6464 right?


<!-- Sent from Reviewable.io -->

2023-02-11 02:31 UTC, crisgarner commented
The updates for https://github.com/proofxyz/EIPs/pull/6/commits/ef4b184ef7194301f8b45d8d39aa587882d7177a are currently on the implementation and interfaces

2023-02-11 02:31 UTC, crisgarner reviewed
> *[Reviewable](https://reviewable.io/reviews/proofxyz/EIPs/6)* status: 0 of 70 files reviewed, 24 unresolved discussions (waiting on @cxkoda)

___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 7 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqSCUa9JuL4GTDH2aa:-NNxF0xW8im-zrOVq4v-:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L7)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

If you make this contract `abstract` you can skip the constructor and leave it to the consuming contract. See also [ERC721Enumerable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/ERC721Enumerable.sol)
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 12 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqSZyG7c01zBAS9jEO:-NNxYskz08cCRX0cDd2r:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L12)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

All variables and functions need at least an `@notice` explaining the basic use/intent of the object. Please also specify all visibilities (i.e. `private` in this case) explicitly and use a leading underscore for `private` and `internal` ones. 
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 15 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqT3l7-KlpGRgag_kn:-NNxHaJy724coGt-pRd_:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L15)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

We can introduce [user-defined value types](https://docs.soliditylang.org/en/latest/types.html#user-defined-value-types) here to make these and the following mapping type safe. i.e. something like 
```
type TokenNonce is uint256;
mapping(uint256 => TokenNonce) private _tokenNonces;
```
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 19 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqTpNDDSJIxgmwdUzG:-NNxHbHr8Dv1JiR25EO9:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L19)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Using the above types, this would translate to `mapping(uint => mapping(TokenNonce => mapping(OwnerNonce => mapping(address => bool))))`
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 26 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqYszb33bN2rCUjKkF:-NNxHdT59A7WsfRLkM4e:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L26)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Not needed for the reference implementation
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 31 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqYuclBrbBBC8jBYHS:-NNxHgM20P3xPnwW51Py:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L31)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Since the reference implementation should be easily reusable we should not add any public functions that are outside the spec, especially if they are as dangerous as this one.
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 41 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqUq8g-_lxhMTyFCsY:-NNxVtjk5CXAMvRulS9j:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L41)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Please use `revert` + [explicit error types](https://docs.soliditylang.org/en/latest/contracts.html#errors) instead of `require` + strings. This makes it more robust because we don't have to deal with strings.
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 45 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqWR6n-yjRXjTuSR8V:-NNxYzlT5EwLTjq86fVI:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L45)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Comment not needed since it is clear from reading the code. Comments should give the reader more information about why you did something instead of explaining what you are doing (the latter should be obvious from the code. if not, it indicates that the code should be revised).
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 67 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqXGT55CuWIlrNlDXw:-NNxX3Y1CCS19_ZOmFNO:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L67)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

It is ok to be lazy here and inherit the docs from the interface by adding
```
/**
* @inheritdoc IERCTBD
* /
```
This also applies to all other functions covered by the interface.
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 72 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqY1Qj35dlV6X4EMT0:-NNxXl8w8cwiwJPoP4nF:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L72)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Since we are not about efficiency at this point, let's make this function public and reuse it in `setExplicitApproval(address, uint[], bool)`
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 73 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqXx3z8P-UL6MPS3qz:-NNxXqxy3UKyOBrPjtVI:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L73)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Same as above regarding error types.
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 97 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqYNlFCuZGSfv6QFV8:-NNxZL2W9aUlkLdTyrbx:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contract [...]

2023-02-13 13:29 UTC, crisgarner reviewed
> Reviewed 67 of 70 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/proofxyz/EIPs/6)* status: 69 of 70 files reviewed, 23 unresolved discussions (waiting on @cxkoda)

___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 44 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqW8DnB5EMXZ10nhJX:-NO7-8edAFNL0w6n60KY:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L44)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Leave all the standard logic to the parent implementation by calling `super.transferFrom(..)` at the end.
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol` line 53 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqX9Nl0BV2RrjZ-AsO:-NO7-AV23PegIhszLuMo:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/src/ERCTBD.sol#L53)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Same as above: reuse the logic from the parent contract.
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/test/ERCTBD.t.sol` line 7 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqZqCT0dPnS8EF4MZf:-NO-tGEK0w6ndiyRq4Xm:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/test/ERCTBD.t.sol#L7)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Please set this up as a test suite that can receive any instance of an `IERCTBD` compatible contract. This allows anyone to reuse these tests on their implementation.
This can be achieved e.g. by having something like
```
contract ERCTBDTest is Test {
    ...
    IERCTBD public immutable token;
    constructor(IERCTBD token_) {
        token = token_;
    }
    ...
}

contract TestableReferenceERCTBD is ERCTBD {
    // actual constructor + mint function
}

contract ReferenceERCTBCTest is ERCTBDTest {
   constructor() ERCTBDTest(new TestableReferenceERCTBD() ){
   }
}
```

</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/test/ERCTBD.t.sol` line 30 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqb4qV4hVCnapQ3qhi:-NO2AgH362h5SKv4S-Wh:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/test/ERCTBD.t.sol#L30)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

Let's use [fuzzed tests](https://book.getfoundry.sh/forge/fuzz-testing) (aka property based testing) instead of hardcoding parameters. 
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/test/ERCTBD.t.sol` line 38 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqbUPi0K-PK29T2AZy:-NO2AhCE4SF8E0HBFbUU:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/test/ERCTBD.t.sol#L38)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

please remove `//setUp`, `//execution`, `//assert` since this is obvious from the code.
</blockquote></details>

Done.
___
*[`assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/test/ERCTBD.t.sol` line 135 at r1](https://reviewable.io/reviews/proofxyz/EIPs/6#-NNqcAFt7ploM_QUW0tX:-NO7-Bzi4yypqrPZEcL3:b-896fix) ([raw file](https://github.com/proofxyz/EIPs/blob/f75cabea3a0d80dd886b968f66165df106d1db3c/assets/eip-draft_multi-operator_per-token_erc721_approval/contracts/test/ERCTBD.t.sol#L135)):*
<details><summary><i>Previously, cxkoda (cxkoda) wrote…</i></summary><blockquote>

All `testSetExplicit` contain a lot of repeated code and should therefore be unified. Remind me to walk you through on slack on how we commonly set up tests to avoid this while remaining readable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-26 15:59 UTC, cxkoda commented
Closing this in favour of https://github.com/proofxyz/erc6464/pull/1

2023-03-26 15:59 UTC, closed without merging